file:D:/Program Files/Git/etc/gitconfig	diff.astextplain.textconv=astextplain
file:D:/Program Files/Git/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:D:/Program Files/Git/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:D:/Program Files/Git/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:D:/Program Files/Git/etc/gitconfig	filter.lfs.required=true
file:D:/Program Files/Git/etc/gitconfig	http.sslbackend=openssl
file:D:/Program Files/Git/etc/gitconfig	http.sslcainfo=d:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
file:D:/Program Files/Git/etc/gitconfig	core.autocrlf=true
file:D:/Program Files/Git/etc/gitconfig	core.fscache=true
file:D:/Program Files/Git/etc/gitconfig	core.symlinks=false
file:D:/Program Files/Git/etc/gitconfig	pull.rebase=false
file:D:/Program Files/Git/etc/gitconfig	credential.helper=manager
file:D:/Program Files/Git/etc/gitconfig	credential.https://dev.azure.com.usehttppath=true
file:D:/Program Files/Git/etc/gitconfig	init.defaultbranch=master
file:C:/Users/Administrator/.gitconfig	credential.https://gitee.com.provider=generic
file:C:/Users/Administrator/.gitconfig	user.name=经淼
file:C:/Users/Administrator/.gitconfig	user.email=ajingmiao@163.com
file:C:/Users/Administrator/.gitconfig	pull.rebase=false
file:C:/Users/Administrator/.gitconfig	safe.directory=%(prefix)///192.168.1.103/code/onlyoffice-plugins/demo-a
file:.git/config	core.repositoryformatversion=0
file:.git/config	core.filemode=false
file:.git/config	core.bare=false
file:.git/config	core.logallrefupdates=true
file:.git/config	core.symlinks=false
file:.git/config	core.ignorecase=true
file:.git/config	remote.origin.url=https://github.com/ajingmiao/onlyoffice-plugin-demo.git
file:.git/config	remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config	branch.main.remote=origin
file:.git/config	branch.main.merge=refs/heads/main
file:.git/config	branch.main.vscode-merge-base=origin/main
file:.git/config	branch.main.vscode-merge-base=origin/main
